// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/Demo.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
